[package]
name = "mitsuba_rs"
version = "0.1.0"
authors = ["beltegeuse <adrien.gruson@gmail.com>"]
edition = "2018"

[dependencies]
xml-rs = "0.8"
cgmath = "0.17" # TODO: Think to remove this dependencies
lazy_static = "1.4"